# Generate a full snapshot of Hassio everyday at 02:00

- alias: snapshot daily

  trigger:
  - at: 02:00
    platform: time

  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    
  action:
  - service: hassio.snapshot_full