- id: '1557659442843'
  alias: Jildou vertrekt van werk (IOS notification)
  trigger:
  - entity_id: person.jildou
    event: leave
    platform: zone
    zone: zone.werk_2
  condition: []
  action:
  - data:
      message: Jildou vertrekt vanaf het Deventer Ziekenhuis naar huis
    service: notify.ios_iphone_van_martijn
- id: '1558030816769'
  alias: Hass.io Snapshot upload to Dropbox
  trigger:
  - at: 03:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
- id: '1558031775450'
  alias: Hass.io full Snapshot daily
  trigger:
  - at: 02:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: hassio.snapshot_full
- alias: Licht WC aan bij motion detection
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_wc
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.wc
  id: c6c1b00b8bfc4d52a008616cf6316800
- alias: Licht WC uit na 3 minuten geen motion detection
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_wc
    to: 'off'
    for:
      minutes: 3
  action:
    service: homeassistant.turn_off
    entity_id: light.wc
  id: 6322b62a911f4dc783eeab0cc48149c2
- id: '1562152939198'
  alias: iOS notificatie wanneer grondvochtigheid van de plant onder de 20% komt (Howea
    Forsteriana)
  trigger:
  - entity_id: person.martijn
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - condition: numeric_state
    entity_id: sensor.howea_forsteriana_mqtt_moisture
    below: '21'
  action:
  - data:
      message: Geef de Howea Forsteriana water! Het vochtgehalte van de grond is 20%
        of lager.
    service: notify.ios_iphone_van_martijn
- id: '1562505227454'
  alias: Batterij iPhone 75% opgeladen
  trigger:
  - above: '74'
    below: '99'
    entity_id: sensor.life360_martijn_batterij
    platform: numeric_state
  condition:
  - condition: state
    entity_id: sensor.life360_martijn_batterij_opladen
    state: 'True'
  - condition: zone
    entity_id: person.martijn
    zone: zone.home
  - condition: time
    after: 08:00
    before: '23:00'
  action:
  - service: notify.google_assistant_broadcast_message
    data_template:
      message: Attentie attentie. De batterij van mijn iPhone is nu voor ongeveer
        75% opgeladen.
- id: '1562505327843'
  alias: Batterij iPhone 100% opgeladen
  trigger:
  - above: '97'
    entity_id: sensor.life360_martijn_batterij
    platform: numeric_state
  condition:
  - condition: state
    entity_id: sensor.life360_martijn_batterij_opladen
    state: 'True'
  - condition: zone
    entity_id: person.martijn
    zone: zone.home
  - condition: time
    after: 08:00
    before: '23:00'
  action:
  - service: notify.google_assistant_broadcast_message
    data_template:
      message: Attentie, attentie. De batterij van mijn iPhone is nu volledig opgeladen.
        Hoera. Hoera. Hoera.
- id: '1562601790356'
  alias: iOS notificatie wanneer grondvochtigheid van de plant onder de 16% komt (Pachira
    Aquatica)
  trigger:
  - entity_id: person.martijn
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - below: '16'
    condition: numeric_state
    entity_id: sensor.pachira_aquatica_mqtt_moisture
  action:
  - data:
      message: Geef de Pachira Aquatica water! Het vochtgehalte 15% of lager.
    service: notify.ios_iphone_van_martijn
- id: '1562870229615'
  alias: ComfoFanS aan wanneer luchtvochtigheid badkamer boven de 80% komt
  trigger:
  - above: '80'
    entity_id: sensor.aqara_humidity_1
    platform: numeric_state
  condition: []
  action:
    service: light.turn_on
    entity_id: light.newkaku_01d610ee_1
- id: '1562870547568'
  alias: Comfofan uit wanneer luchtvochtigheid badkamer onder 80% komt
  trigger:
  - below: '80'
    entity_id: sensor.aqara_humidity_1
    platform: numeric_state
  condition: []
  action:
    service: homeassistant.turn_off
    entity_id: light.newkaku_01d610ee_1
- id: '1563216598554'
  alias: Lichten aan in de woonkamer een half uur voor zonsondergang
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - service: light.turn_on
    entity_id: light.woonkamer
    data:
      brightness: 128
      transition: 600
- id: '1563299208292'
  alias: Googletranslate TTS wanneer wasmachine klaar is
  trigger:
  - entity_id: sensor.wasmachine_washer_machine_state
    from: run
    platform: state
    to: stop
  condition: []
  action:
  - service: notify.google_assistant_broadcast_message
    data_template:
      message: Attentie. Attentie. De wasmachine heeft zijn programma voltooid.
- id: '1563384253797'
  alias: 'iOS notificatie: Batterij Aqara sensor 1 = <5%'
  trigger:
  - below: '5'
    entity_id: sensor.aqara_battery_1
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Vervang de batterij van Aqara sensor 1. Batterij niveau = <5%
    service: notify.ios_iphone_van_martijn
- id: '1563384324743'
  alias: 'iOS notificatie: Batterij Aqara sensor 2 = <5%'
  trigger:
  - below: '5'
    entity_id: sensor.aqara_battery_2
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Vervang de batterij van Aqara sensor 2. Batterij niveau = <5%
    service: notify.ios_iphone_van_martijn
- id: '1563384371262'
  alias: 'iOS notificatie: Batterij Aqara sensor 3 = <5%'
  trigger:
  - below: '5'
    entity_id: sensor.aqara_battery_3
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Vervang de batterij van Aqara sensor 3. Batterij niveau = <5%
    service: notify.ios_iphone_van_martijn
- id: '1563392538020'
  alias: TV on = TV lights
  trigger:
  - entity_id: binary_sensor.samsung_tv_ping
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.woonkamer
    state: 'on'
  action:
  - data:
      brightness: 80
      transition: 10
    entity_id: light.woonkamer
    service: light.turn_on
- id: '1563556966270'
  alias: Als Jildou thuis komt 45 minuten voor zonsondergang of er na = lichten aan
  trigger:
  - entity_id: person.jildou
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - after: sunset
    after_offset: -00:45:00
    condition: sun
  action:
  - data:
      brightness: 120
      transition: 10
    entity_id: light.woonkamer
    service: light.turn_on
- id: '1563557161091'
  alias: Als Martijn thuis komt 45 minuten voor zonsondergang of er na = lichten aan
  trigger:
  - entity_id: person.martijn
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - after: sunset
    after_offset: -00:45:00
    condition: sun
  action:
  - data:
      brightness: 120
      transition: 10
    entity_id: light.woonkamer
    service: light.turn_on
- id: '1563630867807'
  alias: Licht aan in de gang bij motion detecten
  trigger:
  - entity_id: binary_sensor.motion_sensor_gang
    platform: state
    to: 'on'
  condition:
  - after: sunset
    after_offset: -00:45:00
    condition: sun
  action:
  - entity_id: light.gang
    service: light.turn_on
- id: '1563630923199'
  alias: Licht uit in de gang na 1 minuut geen motion detection
  trigger:
  - entity_id: binary_sensor.motion_sensor_gang
    platform: state
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.gang
- id: '1563637461631'
  alias: Radio Soundbar fav 1
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Radio 10
  condition: []
  action:
  - service: shell_command.soundbar_radio_fav1
- id: '1563637806654'
  alias: Radio Soundbar fav 2
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Radio Veronica
  condition: []
  action:
  - service: shell_command.soundbar_radio_fav2
- id: '1563638018088'
  alias: Radio Soundbar fav 3
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Qmusic
  condition: []
  action:
  - service: shell_command.soundbar_radio_fav3
- id: '1563638086795'
  alias: Radio soundbar uit
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Soundbar uit
  condition: []
  action:
  - service: media_player.turn_off
    entity_id: media_player.soundbar_2
- id: '1563640474355'
  alias: Radio Soundbar radio 1
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: NPO 3FM
  condition: []
  action:
  - service: shell_command.soundbar_radio_1
- id: '1563640545749'
  alias: Radio soundbar radio 2
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Skyradio
  condition: []
  action:
  - service: shell_command.soundbar_radio_2
- id: '1563644547326'
  alias: Radio soundbar radio 3
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Qmusic - Het Foute Uur
  condition: []
  action:
  - service: shell_command.soundbar_radio_3
- id: '1563644616076'
  alias: Radio soundbar radio 4
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Radio 10 - Disco Classics
  condition: []
  action:
  - service: shell_command.soundbar_radio_4
- id: '1563707914071'
  alias: Radio soundbar radio 5 - Radio 10 - Guilty Pleasures
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Radio 10 - Guilty Pleasures
  condition: []
  action:
  - service: shell_command.soundbar_radio_5
- id: '1563708013671'
  alias: Radio soundbar radio 6 - Radio 538
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Radio 538
  condition: []
  action:
  - service: shell_command.soundbar_radio_6
- id: '1563708884809'
  alias: Radio soundbar radio 7 - Radio 538
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: NPO Radio 2
  condition: []
  action:
  - service: shell_command.soundbar_radio_7
- id: '1563708924095'
  alias: Radio soundbar radio 8 - Radio 10 - 80's Hits
  trigger:
  - entity_id: input_select.radio_soundbar
    platform: state
    to: Radio 10 - 80's Hits
  condition: []
  action:
  - service: shell_command.soundbar_radio_8
- id: '1563717823204'
  alias: input select naar - maak een keuze - wanneer de Soundbar uit gaat
  trigger:
  - entity_id: media_player.soundbar_2
    platform: state
    to: 'off'
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.radio_soundbar
      option: Maak een keuze
- id: rova-garbage-bio-reminder
  alias: Rova bio container gehaald
  trigger:
  - at: '18:30:00'
    platform: time
  condition:
  - condition: template
    value_template: '{% if (as_timestamp(states(''sensor.rova_bio'')) - as_timestamp(now()))
      < 43200 %}true{% endif %}'
  - condition: template
    value_template: '{% if (as_timestamp(states(''sensor.rova_bio'')) - as_timestamp(now()))
      > 0 %}true{% endif %}'
  action:
  - data_template:
      message: Attentie. Attentie. Morgen wordt de groene container leeg gehaald!
        Vergeet niet de container aan de kant van de straat te zetten.
    service: notify.google_assistant_broadcast_message
- id: rova-garbage-paper-reminder
  alias: Rova papier container gehaald
  trigger:
  - at: '18:30:00'
    platform: time
  condition:
  - condition: template
    value_template: '{% if (as_timestamp(states(''sensor.rova_paper'')) - as_timestamp(now()))
      < 43200 %}true{% endif %}'
  - condition: template
    value_template: '{% if (as_timestamp(states(''sensor.rova_paper'')) - as_timestamp(now()))
      > 0 %}true{% endif %}'
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - data_template:
      message: Attentie. Attentie. Morgen wordt de papier container leeg gehaald!
        Vergeet niet de container aan de kant van de straat te zetten.
    service: notify.google_assistant_broadcast_message
- id: rpi_power_issue
  alias: Power Problem Notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.rpi_power_status
    value_template: '{{ state.attributes.value }}'
    above: 0
    for:
      minutes: 5
  condition:
  action:
  - service: persistent_notification.create
    data_template:
      message: 'RPI Power reported {{ states.sensor.rpi_power_status.state }}. The
        state had changed from {{ trigger.from_state.state }} '
      title: Power Supply Issue
  - service: notify.ios_iphone_van_martijn
    data_template:
      message: RPI Power reported {{ states.sensor.rpi_power_status.state }}. The
        state had  changed from {{ trigger.from_state.state }}
      title: Power Supply Issue
- id: '1563910893213'
  alias: Nieuwe update available
  trigger:
  - platform: state
    entity_id: sensor.latest_version
  condition: []
  action:
  - data:
      message: Version {{ states.sensor.latest_version.state }} is available!
      title: Nieuwe update Home Assistant beschikbaar
    service: notify.ios_iphone_van_martijn
- id: '1564235311997'
  alias: Brievenbus +1
  trigger:
  - entity_id: binary_sensor.openclose_14
    platform: state
    to: 'on'
  condition: []
  action:
  - service: counter.increment
    entity_id: all
- id: '1564235344488'
  alias: Brievenbus reset
  trigger:
  - at: 00:00
    platform: time
  condition: []
  action:
  - service: counter.reset
    entity_id: all
- id: '1564237006508'
  alias: Broadcast message Google Home wanneer brievenbus +1
  trigger:
  - entity_id: binary_sensor.openclose_14
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - data_template:
      message: Attentie. Attentie. Er is een poststuk in de brievenbus gedaan!
    service: notify.google_assistant_broadcast_message
- id: '1564237126538'
  alias: IOS notificatie wanneer brievenbus +1
  trigger:
  - entity_id: binary_sensor.openclose_14
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Je hebt een poststuk ontvangen.
      title: Brievenbus
    service: notify.ios_iphone_van_martijn
- alias: Spotify Volume (Set)
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state | int / 100  }}'
  id: 565feb2c7a8b460fa1710b5bc24c7107
- alias: Spotify Volume (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_volume
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.spotify_volume
      value: '{{  states.sensor.spotify_volume.state | float | round(2) * 100  }}'
  id: 645a419513524fecbec7a665a48b6320
- alias: Spotify Shuffle (Set)
  trigger:
    platform: state
    entity_id: input_boolean.spotify_shuffle
  action:
    service: media_player.shuffle_set
    data_template:
      entity_id: media_player.spotify
      shuffle: '{% if is_state(''input_boolean.spotify_shuffle'', ''off'') %}  false
        {% elif is_state(''input_boolean.spotify_shuffle'', ''on'') %} true {% endif
        %}

        '
  id: 1479d8bbc8244a21818f5428c933092c
- alias: Spotify Shuffle (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_shuffle
  action:
  - service_template: "{% if states.sensor.spotify_shuffle.state == 'False' %}\n \
      \ input_boolean.turn_off\n{% else %}\n  input_boolean.turn_on\n{% endif %}\n"
    data:
      entity_id: input_boolean.spotify_shuffle
  id: c5a686d07ec84750a0ebdda8f62e6fdf
- alias: Spotify Source (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_source
  action:
    service: input_select.select_option
    entity_id: input_select.spotify_source
    data_template:
      option: '{{  states.sensor.spotify_source.state  }}'
  id: 1e8245e5b8d04e42a999c90a7e721f4f
- id: '1564825950855'
  alias: Nieuwe Youtube video kanaal playedby
  trigger:
  - entity_id: sensor.playedby_1
    platform: state
  condition: []
  action:
  - service: counter.increment
    entity_id: counter.playedby
- alias: Nieuwe Youtube video kanaal Blank & Red
  trigger:
  - entity_id: sensor.blank_red_1
    platform: state
  condition: []
  action:
  - service: counter.increment
    entity_id: counter.blank_red
  id: 9ff92d08e57e4515947afacf71bde6a7
- alias: Nieuwe Youtube video kanaal YY
  trigger:
  - entity_id: sensor.yy_1
    platform: state
  condition: []
  action:
  - service: counter.increment
    entity_id: counter.yy
  id: 7ea9901f884b41338ad997860e352dca
- alias: Nieuwe Youtube video kanaal Mic.Rodance
  trigger:
  - entity_id: sensor.mic_rodance_1
    platform: state
  condition: []
  action:
  - service: counter.increment
    entity_id: counter.mic_rodance
  id: 072471c710e0404881486487a0fe9bd2
  id: '1564940486679'
- alias: Snapshot wanneer brievenbus +1
  trigger:
  - entity_id: binary_sensor.openclose_14
    platform: state
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data_template:
      filename: /config/www/snapshots/snapshot_{{ now ().hour }}_{{ now ().minute }}.jpg
      entity_id: camera.voordeur_camera_deurbel
  - delay: 00:00:03
  - service: notify.ios_iphone_van_martijn
    data_template:
      title: Je hebt post bitch!
      message: Wie is deze postbezorger?
      data:
        attachment:
          content-type: jpeg
          url: /local/snapshots/snapshot_{{ now ().hour }}_{{ now ().minute }}.jpg