# Send an iOS notification when there is a new version of Home Assistant

- alias: ios update home assistant

  trigger:
  - platform: state
    entity_id: sensor.latest_version

  action:
  - service: notify.ios_iphone_van_martijn
    data_template:
      title: Version {{ states.sensor.latest_version.state }} is available!    
      message: 'Check the release notes here.'
      data:
        url: 'https://www.home-assistant.io/blog/'
        attachment:
          content-type: jpg
          url: https://moostmartijn.duckdns.org/local/images/update_available.jpg 