# Send a Home Assistant and iOS notification when there is a power issue of the Raspberry Pi

- alias: ios ha power issue

  trigger:
  - platform: numeric_state
    entity_id: sensor.rpi_power_status
    value_template: '{{ state.attributes.value }}'
    above: 0
    for:
      minutes: 5

  action:
  - service: persistent_notification.create
    data_template:
      message: 'RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }} '
      title: Power Supply issue

  - service: notify.ios_iphone_van_martijn
    data_template:
      message: RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }}
      title: Power Supply Issue