# Receive an iOS notification when receiving new mail

- alias: ios brievenbus

  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_14
    to: 'on'

  action:
  - service: notify.ios_iphone_van_martijn
    data_template:
      title: Brievenbus
      message: Je hebt vandaag om {{ now ().hour }}:{{ now ().minute }} een poststuk ontvangen.
      data:
        attachment:
          content-type: png
          url: https://moostmartijn.duckdns.org/local/images/brievenbus.png