# Send the shopping list items as an iOS notification when I enter the shop zones zone.jumbo and zone.albert_heijn

- alias: ios shopping list zones

  trigger:
  - platform: zone
    entity_id: person.martijn
    event: enter
    zone: zone.jumbo
  - platform: zone
    entity_id: person.martijn
    event: enter
    zone: zone.albert_heijn

  condition:
  - condition: template
    value_template: "{{ not is_state('sensor.shopping_list', 'Boodschappen:') }}"

  action: 
  - service: notify.ios_iphone_van_martijn
    data_template:
      message: '{{states.sensor.shopping_list.state}}'
      data:
        push:
          category: "empty_shopping_list" 