# Send an iOS notification when Jildou comes home from work

- alias: ios jildou leaves zone work

  trigger:
  - platform: zone
    entity_id: person.jildou
    event: leave
    zone: zone.werk_2

  action:
  - service: notify.ios_iphone_van_martijn
    data:
      message: Jildou vertrekt vanaf het Deventer Ziekenhuis naar huis
    