# Turn on light.woonkamer 30 minutes before sunset

- alias: light.woonkamer on sunset

  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun

  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
    
  action:
  - service: light.turn_on
    entity_id: light.woonkamer
    data:
      brightness: 128
      transition: 600