# Turn on the lights if someone comes home 30 minutes before sunset or later

- alias: light.woonkamer on home zone sunset

  trigger:
  - platform: zone
    entity_id: person.jildou
    event: enter
    zone: zone.home
  - platform: zone
    entity_id: person.martijn
    event: enter
    zone: zone.home

  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'

  action:
  - service: light.turn_on
    entity_id: light.woonkamer  
    data:
      brightness: 120
      transition: 10
    