# Turn on light.hall when motion is detected

- alias: light hall on motion

  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_hall
    to: 'on'

  condition:
  - condition: time
    after: '06:00:00'
    before: '23:59:00'

  action:
  - service: light.turn_on
    entity_id: light.hall
    