# Turn on light.gang when motion is detected

- alias: light gang on motion

  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_gang
    to: 'on'

  condition:
  - after: sunset
    after_offset: '-00:45:00'
    condition: sun
    
  action:
  - service: light.turn_on
    entity_id: light.gang
    