# Turn off light.gang when no motion is detected for 1 minute

- alias: light gang off motion

  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_gang
    to: 'off'

  action:
  - service: light.turn_off
    entity_id: light.gang