# Increase the counter.brievenbus when receiving new mail

- alias: mailbox counter increment

  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_14
    to: 'on'

  action:
  - service: counter.increment
    entity_id: all