# Turn ComfoFanS off when the humidity in the bathroom drops below 80%

- alias: comfofans off humidity

  trigger:
  - platform: numeric_state
    below: '80'
    entity_id: sensor.aqara_humidity_1

  action:
    service: homeassistant.turn_off
    entity_id: light.newkaku_01d610ee_1