# Turn off samsungtv when mexiabox next is turned off

- alias: samsungtv off mediabox next off

  trigger:
  - platform: state
    entity_id: media_player.mediabox_next
    from: 'on'
    to: 'idle'

  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.samsung_smart_tv